# -*- coding: utf-8 -*-
"""Customer_Segmentation_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vJBIcgeM8AAZu7S5HPz-X2gxKGVGEV6G
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('C:/Users/HP/Agileology_Works/Data_Science_Works/Customer_Segmentation_ML_Project/Online_Retail.csv', encoding='latin1')

print(df.head())

print(df.shape)

print(df.columns)

print(df.dtypes)

print(df.isnull().sum())

print(df.isnull().sum()/len(df)*100)

print(df.describe())

print("Total unique customers are:", df['CustomerID'].nunique())

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], format='%d-%m-%Y %H:%M')
print(df['InvoiceDate'].min())
print(df['InvoiceDate'].max())

df = df.dropna(subset=['CustomerID'])

print("Rows after removing null CustomerID:", df.shape[0])

df = df[df['Quantity'] > 0]

print("Rows after removing negative Quantity:", df.shape[0])

# Remove Zero or Negative Unit Price
df = df[df['UnitPrice'] > 0]

print("Rows after removing invalid UnitPrice:", df.shape[0])

# — Remove Cancelled Invoices

df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]

print("Rows after removing cancelled invoices:", df.shape[0])

# Fix CustomerID Data Type
df['CustomerID'] = df['CustomerID'].astype(int)

# Confirm Clean Data

print("Final dataset shape:", df.shape)
print("\nMissing values after cleaning:")
print(df.isnull().sum())
print("\nQuantity min value:", df['Quantity'].min())
print("UnitPrice min value:", df['UnitPrice'].min())

# Quick Sanity Check
print(df.describe())

#TotalAmount
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

# Set the Reference Date

reference_date = df['InvoiceDate'].max() + pd.Timedelta(days=1)
print("Reference date:", reference_date)

#Build the RFM Table

rfm = df.groupby('CustomerID').agg(
    Recency=('InvoiceDate', lambda x: (reference_date - x.max()).days),
    Frequency=('InvoiceNo', 'nunique'),
    Monetary=('TotalAmount', 'sum')
).reset_index()

print(rfm.head())
print("\nRFM table shape:", rfm.shape)

print(rfm.describe())

print("\nAny nulls in RFM?")
print(rfm.isnull().sum())

# Check for Outliers Visually

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

axes[0].boxplot(rfm['Recency'])
axes[0].set_title('Recency')

axes[1].boxplot(rfm['Frequency'])
axes[1].set_title('Frequency')

axes[2].boxplot(rfm['Monetary'])
axes[2].set_title('Monetary')

plt.suptitle('RFM Outlier Check')
plt.tight_layout()
plt.show()

print(rfm.head())

print(rfm.shape)

print(rfm.describe())

"""#  Handle Outliers + Scale the Data"""

# Remove Outliers Using IQR Method
Q1 = rfm[['Recency', 'Frequency', 'Monetary']].quantile(0.25)
Q3 = rfm[['Recency', 'Frequency', 'Monetary']].quantile(0.75)
IQR = Q3 - Q1

print("Q1:\n", Q1)
print("\nQ3:\n", Q3)
print("\nIQR:\n", IQR)

#  Define Outlier Boundaries
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("\nLower Bound:\n", lower_bound)
print("\nUpper Bound:\n", upper_bound)

# Filter Out Outliers

rfm_cleaned = rfm[
    (rfm['Recency'] >= lower_bound['Recency']) & (rfm['Recency'] <= upper_bound['Recency']) &
    (rfm['Frequency'] >= lower_bound['Frequency']) & (rfm['Frequency'] <= upper_bound['Frequency']) &
    (rfm['Monetary'] >= lower_bound['Monetary']) & (rfm['Monetary'] <= upper_bound['Monetary'])
]

print("Customers before outlier removal:", rfm.shape[0])
print("Customers after outlier removal:", rfm_cleaned.shape[0])
print("Outliers removed:", rfm.shape[0] - rfm_cleaned.shape[0])

#  Check After Outlier Removal

print(rfm_cleaned.describe())

# Scale the Features

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

rfm_scaled = scaler.fit_transform(rfm_cleaned[['Recency', 'Frequency', 'Monetary']])

rfm_scaled = pd.DataFrame(rfm_scaled, columns=['Recency', 'Frequency', 'Monetary'])

print(rfm_scaled.head())
print("\nScaled data describe:")
print(rfm_scaled.describe())

#  Verify Scaling Worked
print("Mean after scaling (should be ~0):")
print(rfm_scaled.mean())

print("\nStd after scaling (should be ~1):")
print(rfm_scaled.std())

rfm_cleaned.shape

""" Finding Optimal K Using Elbow Method"""

# Import K-Means

from sklearn.cluster import KMeans
import warnings
warnings.filterwarnings('ignore')

# Run K-Means for K = 1 to 10

inertia_values = []

for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(rfm_scaled)
    inertia_values.append(kmeans.inertia_)
    print(f"K={k} --> Inertia: {kmeans.inertia_:.2f}")

# Plot the Elbow Curve

plt.figure(figsize=(10, 5))
plt.plot(range(1, 11), inertia_values, marker='o', color='blue', linewidth=2, markersize=8)
plt.title('Elbow Method - Finding Optimal K', fontsize=14)
plt.xlabel('Number of Clusters (K)', fontsize=12)
plt.ylabel('Inertia', fontsize=12)
plt.xticks(range(1, 11))
plt.grid(True)
plt.show()

# Confirm with Silhouette Score

from sklearn.metrics import silhouette_score

silhouette_scores = []

for k in range(2, 11):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(rfm_scaled)
    score = silhouette_score(rfm_scaled, labels)
    silhouette_scores.append(score)
    print(f"K={k} --> Silhouette Score: {score:.4f}")

plt.figure(figsize=(10, 5))
plt.plot(range(2, 11), silhouette_scores, marker='s', color='green', linewidth=2, markersize=8)
plt.title('Silhouette Score - Finding Optimal K', fontsize=14)
plt.xlabel('Number of Clusters (K)', fontsize=12)
plt.ylabel('Silhouette Score', fontsize=12)
plt.xticks(range(2, 11))
plt.grid(True)
plt.show()

"""# Apply K-Means with K=3"""

# Train the Final K-Means Model

kmeans_final = KMeans(n_clusters=3, random_state=42, n_init=10)
kmeans_final.fit(rfm_scaled)

# Assign Cluster Labels to Each Customer
rfm_cleaned = rfm_cleaned.copy()
rfm_cleaned['Cluster'] = kmeans_final.labels_
print(rfm_cleaned.head(10))

# Check Cluster Sizes

print("Number of customers in each cluster:")
print(rfm_cleaned['Cluster'].value_counts().sort_index())

#  Get the Inertia and Silhouette Score for Final Model
from sklearn.metrics import silhouette_score

final_inertia = kmeans_final.inertia_
final_silhouette = silhouette_score(rfm_scaled, kmeans_final.labels_)

print(f"Final Model Inertia: {final_inertia:.2f}")
print(f"Final Model Silhouette Score: {final_silhouette:.4f}")

# Analyze Each Cluster's Characteristics

cluster_summary = rfm_cleaned.groupby('Cluster')[['Recency', 'Frequency', 'Monetary']].mean().round(2)
print(cluster_summary)

# Get the Cluster Centroids

centroids = pd.DataFrame(
    kmeans_final.cluster_centers_,
    columns=['Recency', 'Frequency', 'Monetary']
)
centroids.index.name = 'Cluster'
print("Cluster Centroids (Scaled):")
print(centroids.round(4))

# Add Cluster Labels (Name Each Cluster)

cluster_labels = {
    0: 'Cluster 0',  # We'll rename after seeing summary
    1: 'Cluster 1',
    2: 'Cluster 2'
}

rfm_cleaned['Cluster_Name'] = rfm_cleaned['Cluster'].map(cluster_labels)
print(rfm_cleaned['Cluster_Name'].value_counts())

#updating cluster names with these proper labels:

cluster_labels = {
    0: 'Regular Customers',
    1: 'At-Risk Customers',
    2: 'Premium Customers'
}

rfm_cleaned['Cluster_Name'] = rfm_cleaned['Cluster'].map(cluster_labels)
print(rfm_cleaned['Cluster_Name'].value_counts())

#  Visualizations

# Cluster Size Bar Chart

plt.figure(figsize=(8, 5))
cluster_counts = rfm_cleaned['Cluster_Name'].value_counts()
colors = ['#2ecc71', '#e74c3c', '#3498db']
plt.bar(cluster_counts.index, cluster_counts.values, color=colors, edgecolor='black', width=0.5)
plt.title('Number of Customers in Each Cluster', fontsize=14)
plt.xlabel('Cluster', fontsize=12)
plt.ylabel('Number of Customers', fontsize=12)
for i, v in enumerate(cluster_counts.values):
    plt.text(i, v + 20, str(v), ha='center', fontsize=11, fontweight='bold')
plt.tight_layout()
plt.show()

# Scatter Plot: Recency vs Monetary
plt.figure(figsize=(10, 6))
colors_map = {0: '#2ecc71', 1: '#e74c3c', 2: '#3498db'}
for cluster in rfm_cleaned['Cluster'].unique():
    subset = rfm_cleaned[rfm_cleaned['Cluster'] == cluster]
    plt.scatter(
        subset['Recency'],
        subset['Monetary'],
        c=colors_map[cluster],
        label=cluster_labels[cluster],
        alpha=0.6,
        s=40
    )
plt.title('Customer Segments: Recency vs Monetary', fontsize=14)
plt.xlabel('Recency (Days since last purchase)', fontsize=12)
plt.ylabel('Monetary (Total Spend £)', fontsize=12)
plt.legend(fontsize=11)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Scatter Plot: Frequency vs Monetary
plt.figure(figsize=(10, 6))
for cluster in rfm_cleaned['Cluster'].unique():
    subset = rfm_cleaned[rfm_cleaned['Cluster'] == cluster]
    plt.scatter(
        subset['Frequency'],
        subset['Monetary'],
        c=colors_map[cluster],
        label=cluster_labels[cluster],
        alpha=0.6,
        s=40
    )
plt.title('Customer Segments: Frequency vs Monetary', fontsize=14)
plt.xlabel('Frequency (Number of Purchases)', fontsize=12)
plt.ylabel('Monetary (Total Spend £)', fontsize=12)
plt.legend(fontsize=11)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

#  Cluster Characteristics Heatmap

plt.figure(figsize=(8, 5))
sns.heatmap(
    cluster_summary,
    annot=True,
    fmt='.2f',
    cmap='YlOrRd',
    linewidths=0.5,
    linecolor='gray'
)
plt.title('Cluster Characteristics Heatmap (RFM Averages)', fontsize=14)
plt.tight_layout()
plt.show()

print("Variance of each RFM feature:")
print(rfm_cleaned[['Recency', 'Frequency', 'Monetary']].var().round(2))

print("Variance of each RFM feature:")
print(rfm_cleaned[['Recency', 'Frequency', 'Monetary']].var().round(2))

highest_var = rfm_cleaned[['Recency', 'Frequency', 'Monetary']].var().idxmax()
print(f"\nFeature with highest variance: {highest_var}")

from scipy.spatial.distance import cdist

# Calculate distance of each customer from their own cluster centroid
distances = cdist(rfm_scaled, kmeans_final.cluster_centers_, metric='euclidean')
print("Distance array shape:", distances.shape)

# Get each customer's distance to THEIR OWN cluster centroid only
rfm_cleaned['Distance_to_Centroid'] = distances[
    np.arange(len(rfm_cleaned)),
    kmeans_final.labels_
]
print(rfm_cleaned[['CustomerID', 'Cluster_Name', 'Distance_to_Centroid']].head(10))

# Find top 10 customers farthest from their centroid
farthest_customers = rfm_cleaned.nlargest(10, 'Distance_to_Centroid')[
    ['CustomerID', 'Cluster_Name', 'Recency', 'Frequency', 'Monetary', 'Distance_to_Centroid']
]
print("\nTop 10 customers farthest from their cluster centroid:")
print(farthest_customers.round(2))

# Visualize farthest points on the scatter plot
plt.figure(figsize=(10, 6))

colors_map = {0: '#2ecc71', 1: '#e74c3c', 2: '#3498db'}

for cluster in rfm_cleaned['Cluster'].unique():
    subset = rfm_cleaned[rfm_cleaned['Cluster'] == cluster]
    plt.scatter(
        subset['Recency'],
        subset['Monetary'],
        c=colors_map[cluster],
        label=cluster_labels[cluster],
        alpha=0.5,
        s=30
    )

# Highlight the farthest 10 points in black
plt.scatter(
    farthest_customers['Recency'],
    farthest_customers['Monetary'],
    c='black',
    marker='X',
    s=150,
    zorder=5,
    label='Farthest Points (Outliers)'
)

plt.title('Outlier Detection - Farthest Points from Centroids', fontsize=14)
plt.xlabel('Recency (Days since last purchase)', fontsize=12)
plt.ylabel('Monetary (Total Spend £)', fontsize=12)
plt.legend(fontsize=10)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Summary statistics of farthest customers
print("\nAverage RFM of farthest customers vs overall:")
print("\nOverall averages:")
print(rfm_cleaned[['Recency', 'Frequency', 'Monetary']].mean().round(2))
print("\nFarthest customers averages:")
print(farthest_customers[['Recency', 'Frequency', 'Monetary']].mean().round(2))
print("Done")